name: Dev branch to deploy ARM storage template

on: 
 push:
   branches:
    - dev
   paths-ignore: 
    -  '.github/**'

env:
  AZURE_RG: RG-GITHUB-ACTIONS-DEV
  AZURE_RG_TEST: RG-GITHUB-ACTIONS-DEV
  AZURE_LOCATION: westeurope

jobs:
  build:
    name: Build and Check ARM template
    runs-on: windows-2019
    
    steps:
      # Checkout code
    - name: Import du repository 
      uses: actions/checkout@v2

      # Log into Azure with PS Support enabled
    - name: Log in Azure 
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
        
    - name: Check ARM Template integretiy
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $Parameters = @{
              ResourcegroupName     = "${{ env.AZURE_RG_TEST }}"
              Templatefile          = ".\ARM\storage_template.json"
              TemplateParameterfile = ".\ARM\storage_parameters.json"
              Mode                  = 'Incremental'
            }
            $Parameters
            $Result = Get-AzResourceGroupDeploymentWhatIfResult @Parameters
            $result
        azPSVersion: '3.1.0'
       
    - name: Copy artifacts to folder
      shell: pwsh
      run: |
       mkdir .\ARMArtifacts
       copy-item .\ARM\*.* .\ARMArtifacts
       
    - name: Upload Artifacts
      uses: actions/upload-artifact@main
      with:
       name: ARM Template
       path: ARMArtifacts/

  deploy:
      name: Deploy ARM template
      runs-on: ubuntu-latest
      needs: build
        
      steps:
        - name: Create ARM Template Artifacts folder
          run: |
           mkdir ARMArtifacts
           
        - name: Download ARM Template Artifacts
          uses: actions/download-artifact@v2
          with:
           name: ARM Template
           path: ARMArtifacts/
           
           # Log into Azure with PS Support enabled
        - name: Log in Azure 
          uses: azure/login@v1.1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

          # Deploy ARM Template
        - name: Deploiement du template ARM
          id: deployarm
          uses: azure/arm-deploy@v1
          with:
            scope: resourcegroup
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
            resourceGroupName: ${{ secrets.AZURE_RG }}
            template: ./ARMArtifacts/storage_template.json
            parameters: ./ARMArtifacts/storage_parameters.json
            deploymentName: GADeployment-01
            deploymentMode: Incremental
            
               # output containerName variable from template
        - name: Output containerName variable from template 
          run: echo ${{ steps.deployarm.outputs.storageAccountName }}

      # Deploy ARM template
   # - name: Run ARM deploy
    #  uses: azure/arm-deploy@v1
     # id: deploy
      #with:
       # subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        #resourceGroupName: ${{ secrets.AZURE_RG }}
        #template: ./azuredeploy.json
        #parameters: storageAccountType=Standard_LRS

      # output containerName variable from template
    #- run: echo ${{ steps.deploy.outputs.storageAccountName }}
      
